# Generated by Django 3.0.3 on 2020-05-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
