# Generated by Django 3.0.3 on 2020-05-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200506_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(auto_now=True, verbose_name='予定完了日時'),
        ),
        migrations.AddField(
            model_name='todo',
            name='large_class',
            field=models.CharField(default='general', max_length=100, verbose_name='LargeClass'),
        ),
        migrations.AddField(
            model_name='todo',
            name='middle_class',
            field=models.CharField(default='general', max_length=100, verbose_name='MiddleClass'),
        ),
        migrations.AddField(
            model_name='todo',
            name='remarks',
            field=models.TextField(blank=True, max_length=100, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='todo',
            name='small_class',
            field=models.CharField(default='general', max_length=100, verbose_name='SmallClass'),
        ),
    ]
