# Generated by Django 3.0.3 on 2020-05-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200507_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(verbose_name='予定完了日時'),
        ),
    ]
